# This is a basic workflow to help you get started with Actions

name: ZJU-daily_check_in

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
     - cron: '0 23 * * *'

